[package]
name = "KS-Ping-Bot"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
log = "0.4.27"
simple-logging = "2.0.2"
teloxide = { version = "0.15.0", features = ["macros"] }
tokio = { version = "1.8", features = ["rt-multi-thread", "macros"] }
